server:
  port: 9080

# Config for Eureka server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/,http://localhost:7072/eureka/
